export const soccerSchedule = [
  { date: "2026-08-29", day: "Sat", opponent: "Marist", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Plan TBD", notes: "" },
  { date: "2026-09-04", day: "Fri", opponent: "UCSB", location: "Home", competition: "Non-conference", kickoff: "TBD", venue: "Charles F. Berman Field", priority: true, travelStatus: "Book Ithaca", notes: "Priority home match" },
  { date: "2026-09-08", day: "Tue", opponent: "Akron", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Plan TBD", notes: "" },
  { date: "2026-09-12", day: "Sat", opponent: "Open/TBD", location: "TBD", competition: "Open/TBD", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Hold", notes: "" },
  { date: "2026-09-15", day: "Tue", opponent: "Pitt", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "Ambrose Urbanic Field", priority: true, travelStatus: "Pittsburgh", notes: "Priority away match" },
  { date: "2026-09-19", day: "Sat", opponent: "Western Michigan", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Plan TBD", notes: "" },
  { date: "2026-09-22", day: "Tue", opponent: "Binghamton", location: "Home", competition: "Non-conference", kickoff: "TBD", venue: "Charles F. Berman Field", priority: false, travelStatus: "Ithaca", notes: "" },
  { date: "2026-09-26", day: "Sat", opponent: "Harvard", location: "Home", competition: "Ivy League", kickoff: "TBD", venue: "Charles F. Berman Field", priority: true, travelStatus: "Family Weekend", notes: "Family Weekend anchor match" },
  { date: "2026-09-29", day: "Tue", opponent: "Open/TBD", location: "TBD", competition: "Open/TBD", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Hold", notes: "" },
  { date: "2026-10-03", day: "Sat", opponent: "Brown", location: "Away", competition: "Ivy League", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Providence", notes: "" },
  { date: "2026-10-06", day: "Tue", opponent: "UMass", location: "Home", competition: "Non-conference", kickoff: "TBD", venue: "Charles F. Berman Field", priority: false, travelStatus: "Ithaca", notes: "" },
  { date: "2026-10-10", day: "Sat", opponent: "Penn", location: "Home", competition: "Ivy League", kickoff: "TBD", venue: "Charles F. Berman Field", priority: false, travelStatus: "Ithaca", notes: "" },
  { date: "2026-10-13", day: "Tue", opponent: "Colgate", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Hamilton", notes: "" },
  { date: "2026-10-17", day: "Sat", opponent: "Princeton", location: "Away", competition: "Ivy League", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Princeton", notes: "" },
  { date: "2026-10-20", day: "Tue", opponent: "Bucknell", location: "Away", competition: "Non-conference", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Lewisburg", notes: "" },
  { date: "2026-10-24", day: "Sat", opponent: "Dartmouth", location: "Home", competition: "Ivy League", kickoff: "TBD", venue: "Charles F. Berman Field", priority: true, travelStatus: "Ithaca", notes: "Priority home match" },
  { date: "2026-10-31", day: "Sat", opponent: "Yale", location: "Away", competition: "Ivy League", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "New Haven", notes: "" },
  { date: "2026-11-07", day: "Sat", opponent: "Columbia", location: "Home", competition: "Ivy League", kickoff: "TBD", venue: "Charles F. Berman Field", priority: false, travelStatus: "Ithaca", notes: "" },
  { date: "2026-11-13", day: "Fri", opponent: "Postseason/TBD", location: "TBD", competition: "Postseason/TBD", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Hold", notes: "" },
  { date: "2026-11-15", day: "Sun", opponent: "Postseason/TBD", location: "TBD", competition: "Postseason/TBD", kickoff: "TBD", venue: "TBD", priority: false, travelStatus: "Hold", notes: "" }
];